export const planets = [
  {
    name: "Mercury",
    mass: "3.30 × 10²³ kg",
    gravity: 3.7,
    radius: "2,439 km",
    weightRatio: 0.38,
    funFact: "Mercury has the shortest year of all the planets.",
    image: "/public/images/mercury.png",
  },
  {
    name: "Venus",
    mass: "4.87 × 10²⁴ kg",
    gravity: 8.87,
    radius: "6,052 km",
    weightRatio: 0.91,
    funFact: "Venus rotates in the opposite direction to most planets.",
    image: "/public/images/venus.png",
  },
  {
    name: "Earth",
    mass: "5.97 × 10²⁴ kg",
    gravity: 9.81,
    radius: "6,371 km",
    weightRatio: 1,
    funFact: "Earth is the only planet known to support life.",
    image: "/public/images/earth.png",
  },
  {
    name: "Mars",
    mass: "6.42 × 10²³ kg",
    gravity: 3.71,
    radius: "3,389 km",
    weightRatio: 0.38,
    funFact: "Mars is home to Olympus Mons, the tallest volcano in the solar system.",
    image: "/public/images/mars.png",
  },
  {
    name: "Jupiter",
    mass: "1.90 × 10²⁷ kg",
    gravity: 24.79,
    radius: "69,911 km",
    weightRatio: 2.34,
    funFact: "Jupiter has the strongest gravity of all the planets.",
    image: "/public/images/jupiter.png",
  },
  {
    name: "Saturn",
    mass: "5.68 × 10²⁶ kg",
    gravity: 10.44,
    radius: "58,232 km",
    weightRatio: 1.06,
    funFact: "Saturn could float in water if a bathtub big enough existed.",
    image: "/public/images/saturn.png",
  },
  {
    name: "Uranus",
    mass: "8.68 × 10²⁵ kg",
    gravity: 8.69,
    radius: "25,362 km",
    weightRatio: 0.92,
    funFact: "Uranus rotates on its side, unlike any other planet.",
    image: "/public/images/uranus.png",
  },
  {
    name: "Neptune",
    mass: "1.02 × 10²⁶ kg",
    gravity: 11.15,
    radius: "24,622 km",
    weightRatio: 1.19,
    funFact: "Neptune has the fastest winds in the solar system.",
    image: "/public/images/neptune.png",
  },
];
